### ISSUE TITLE
v0.1.2 TODO

### ISSUE THREAD

**Issue by egeakman** [egeakman/python-docs-bootstrapper#6]
- [x] Don't wait the whole repo to be cloned until raising "branch x not found in upstream", report immediately (#2)
- [x] Better pre-commit workflow and updated tests (#2)
- [x] Better packaging (#4)
- [x] Optimized folder discovery and creation (#2)
- Minor changes

Messages originally from #2:

- I'm a *little* busy with my college applications right now, so this PR may take a while...
