### ISSUE TITLE
v0.1.3 TODO

### ISSUE THREAD

**Issue by egeakman** [egeakman/python-docs-bootstrapper#8]
- [ ] Verbose option
- [ ] Add option to use custom data (Makefile, README, gitignore)
- [ ] Tips and checklist for translation maintainers (#7)
- [ ] "Why use python-docs-bootstrapper" section in the README (#1 and #7)
